name: Docker Security Scan

on:
  push:
    branches:
      - "master"

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Run Docker security scan
        uses: anchore/scan-action@v2
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/project-ci/cd:latest
