name: Docker Security Scan and Push

on:
  push:
    branches:
      - "master"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker buildx build --tag ${{ secrets.DOCKERHUB_USERNAME }}/project-web:latest .

      - name: Run Docker security scan
        uses: anchore/scan-action@v2
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/project-web:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/project-web:latest


